server:
  port: 8081
spring:
  application:
    name: order-api
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: org.postgresql.Driver
       url: jdbc:postgresql://ec2-3-211-221-185.compute-1.amazonaws.com:5432/dbk3bq6qe559gg?sslmode=disable
    username: lgtbxzutnqmciv
    password: ee080e942c156f0c5427ef52e9a73d1616e396b0dc28ad07bae93d5668f331be
  jpa:
    generate-ddl: 'false'
    database: POSTGRESQL
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
          lob:
            non_contextual_creation: 'true'
      org:
        hibernate:
          flushMode: COMMIT
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      continue-on-error: 'false'
      platform: postgresql


